version: '3'
services:
  api:
    container_name: "rest_api_${NODE_ENV}"
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - 3000:3000
    # volumes:
    #   - ./:/usr/src/app
    restart: unless-stopped